apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ template "nginx.fullname" . }}
spec:
  capacity:
    storage: 3Gi 
  accessModes:
    - ReadWriteMany 
  persistentVolumeReclaimPolicy: Retain 
  nfs: 
    path: /opt/nfs 
    server: nfs.f22 
    readOnly: false
