kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name:  {{ template "nginx.fullname" . }}
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
